name: FlexiAutoClick
main: FlexiAutoClick.Main
version: 1.0.6
author: LcG
description: Plugin de AutoClick
api-version: 1.13

commands:
  flexiautoclick:
    description: Ativa ou desativa o AutoClick
    aliases: [autoclick, fautoclick]
    usage: /<command> [reload]

permissions:
  autoclick.use:
    description: Permissao para usar o AutoClick
    default: true
  autoclick.admin:
    description: Permissao para recarregar o plugin
    default: op
